# -*- coding: utf-8 -*-
"""Prova1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14nPgnJK3nWzCo-q--ht24x1tSqf2W3mq

### INSTRUÇÕES

 - Fazer os exercícios em um arquivo notebook (de extensão *.ipynb)  
 - Exercícios que pedem entrada de usuário deverão ter valores fixados. Exemplo:  
    num = 6 #int(input('Digite um número inteiro')
 - As questões deverão ser respondidas em ordem
 - Todas as questões deverão ter uma explicação breve de como você pensou na solução
 - Cópias de soluções zerarão a questão dos dois fraudadores
 - Cópias de outros lugares zerarão a questão.
 - Uso de recursos não vistos em aula zerarão a questão.
 - Colocar seu nome, curso e dia da semana no início do notebook
"""



"""### Dados
Nome: Mateus Andrade  
Curso:  Ciencia da computacao

Dia da semana:  segunda
"""





"""1)	Faça um programa que peça o ano de nascimento e mostra a idade do usuário no fim de 2025 e o ano que esse usuário fez ou fará 50 anos.

Primeiro eu peguei o ano de nascimento fixo (não usar input). Depois calculei a idade em 2025 subtraindo o ano de nascimento. Pra saber o ano que a pessoa faz 50 anos, somo 50 ao ano de nascimento.
"""

ano_nascimento = 2000
idade_em_2025 = 2025 - ano_nascimento
ano_50_anos = ano_nascimento + 50

print(f"Em 2025 você terá {idade_em_2025} anos.")
print(f"Você fez ou fará 50 anos em {ano_50_anos}.")



"""2)	 Faça um programa que peça números inteiros ao usuário e conta quantos números positivos e quantos números negativos foram digitados. O programa deverá parar quando o número zero for digitado, mostrando na tela os resultados. Além disso, o programa deverá informar se há mais números positivos, mais números negativos ou se há a mesma quantidade.

Eu fixei uma lista de números porque não pode usar input. Depois usei um for para contar positivos e negativos. Quando o número é 0, eu paro. Depois mostro quem apareceu mais.
"""

numeros = [5, -3, 7, -1, -4, 2, 0]
positivos = 0
negativos = 0

for num in numeros:
    if num == 0:
        break
    if num > 0:
        positivos += 1
    else:
        negativos += 1

print(f"Quantidade de números positivos: {positivos}")
print(f"Quantidade de números negativos: {negativos}")

if positivos > negativos:
    print("Existem mais números positivos.")
elif negativos > positivos:
    print("Existem mais números negativos.")
else:
    print("Existem a mesma quantidade de números positivos e negativos.")



"""3) 	Faça um programa que converta a temperatura de graus Celsius para graus Farenheit ou vice-versa. O programa deverá perguntar se a temperatura de entrada está em Celsius ou Farenheit e mostrar a temperatura digitada convertida para a outra unidade. Fórmulas úteis:  $$C=\frac{5(F-32)}{9}$$,   $$F=\frac{9C}{5}+32$$.

Fixei o valor da temperatura e o tipo (se é Celsius ou Farenheit). Aí fiz a conversão usando as fórmulas que foram dadas.
"""

temperatura = 30
tipo = "C"

if tipo == "C":
    fahrenheit = (9 * temperatura) / 5 + 32
    print(f"{temperatura} graus Celsius é igual a {fahrenheit} graus Farenheit.")
elif tipo == "F":
    celsius = 5 * (temperatura - 32) / 9
    print(f"{temperatura} graus Farenheit é igual a {celsius} graus Celsius.")
else:
    print("Tipo de temperatura inválido.")



"""4) 	Faça um programa que, dado um número n maior que 5, mostra a primeira letra do seu nome feita com n linhas contendo a letra x. Esse programa deverá ter, no máximo, 4 laços de repetição.
Exemplo: n = 6 (letra A):

```
Digite um número maior que 5: 6
      x     
     x x    
    x   x   
   xxxxxxx  
  x       x
 x         x
```

Fixei o n e usei alguns for's para desenhar. Eu desenhei linha por linha, pensando no espaço e no "x".
"""

n = 6

for i in range(n):
    if i == 0:
        print(" " * (n - i) + "x")
    elif i == 1:
        print(" " * (n - i) + "x x")
    elif i == 2:
        print(" " * (n - i) + "x   x")
    elif i == 3:
        print(" " * (n - i) + "xxxxxxx")
    else:
        print(" " * (n - i) + "x" + " " * (2 * i - 1) + "x")



"""Faça um programa que mostre o seguinte padrão na tela, dado um número n:

Digite um número inteiro positivo: 6  
1  
7 2  
12 8 3  
16 13 9 4  
19 17 14 10 5  
21 20 18 15 11 6

Digite um número inteiro positivo: 4  
1  
5 2  
8 6 3  
10 9 7 4

Fixei o número n. Depois usei for para ir preenchendo a matriz seguindo o padrão de crescimento dos números.
"""

n = 6

atual = 1
for linha in range(n):
    num = atual
    for coluna in range(linha + 1):
        print(num, end=" ")
        num -= 1
        atual += 1
    print()

